services:
  - type: web
    name: healthconnect-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: DEMO_MODE
        value: "true"
      - key: JWT_SECRET
        generateValue: true
