// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clbmvfbfzneqruwijxvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsYm12ZmJmem5lcXJ1d2lqeHZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1Mjg0ODQsImV4cCI6MjA1MzEwNDQ4NH0.s6lwW_0Tsd3B7XqxErCp0Yjlx92X4f77lvptMEidaDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);